# Generated by Django 5.2 on 2025-06-20 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='img',
            field=models.TextField(default=''),
        ),
    ]
