# Generated by Django 5.2 on 2025-06-12 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonios', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonio',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
