# Generated by Django 5.2 on 2025-06-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='img',
            field=models.TextField(blank=True, null=True),
        ),
    ]
