# Generated by Django 5.2 on 2025-06-12 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='nivel',
            field=models.CharField(choices=[('medio', 'Medio'), ('principiante', 'Principiante'), ('avanzado', 'Avanzado')], max_length=50),
        ),
        migrations.AlterField(
            model_name='juegos',
            name='dificultad',
            field=models.CharField(choices=[('facil', 'Facil'), ('intermedio', 'Intermedio'), ('dificil', 'Dificil')], max_length=50),
        ),
    ]
