# Generated by Django 5.2 on 2025-06-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_alter_curso_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='img',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='juegos',
            name='img',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nivel',
            field=models.CharField(choices=[('principiante', 'Principiante'), ('medio', 'Medio'), ('avanzado', 'Avanzado')], max_length=50),
        ),
        migrations.AlterField(
            model_name='juegos',
            name='dificultad',
            field=models.CharField(choices=[('dificil', 'Dificil'), ('intermedio', 'Intermedio'), ('facil', 'Facil')], max_length=50),
        ),
    ]
