# Generated by Django 5.2 on 2025-06-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0007_alter_curso_nivel_alter_juegos_dificultad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='nivel',
            field=models.CharField(choices=[('medio', 'Medio'), ('principiante', 'Principiante'), ('avanzado', 'Avanzado')], max_length=50),
        ),
    ]
