# Generated by Django 5.2 on 2025-06-20 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0008_alter_curso_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='nivel',
            field=models.CharField(choices=[('avanzado', 'Avanzado'), ('principiante', 'Principiante'), ('medio', 'Medio')], max_length=50),
        ),
        migrations.AlterField(
            model_name='juegos',
            name='dificultad',
            field=models.CharField(choices=[('intermedio', 'Intermedio'), ('facil', 'Facil'), ('dificil', 'Dificil')], max_length=50),
        ),
    ]
