# Generated by Django 5.2 on 2025-06-20 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0009_alter_curso_nivel_alter_juegos_dificultad'),
        ('usuarios', '0002_usuario_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='nivel',
            field=models.CharField(choices=[('principiante', 'Principiante'), ('medio', 'Medio'), ('avanzado', 'Avanzado')], max_length=50),
        ),
        migrations.AlterField(
            model_name='juegos',
            name='dificultad',
            field=models.CharField(choices=[('facil', 'Facil'), ('dificil', 'Dificil'), ('intermedio', 'Intermedio')], max_length=50),
        ),
        migrations.CreateModel(
            name='CalificacionCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.IntegerField(default=0)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha_calificacion', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.curso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
    ]
