# Generated by Django 5.2 on 2025-06-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0011_alter_juegos_dificultad_calificacionjuego'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='nivel',
            field=models.CharField(choices=[('medio', 'Medio'), ('avanzado', 'Avanzado'), ('principiante', 'Principiante')], max_length=50),
        ),
        migrations.AlterField(
            model_name='juegos',
            name='dificultad',
            field=models.CharField(choices=[('facil', 'Facil'), ('dificil', 'Dificil'), ('intermedio', 'Intermedio')], max_length=50),
        ),
    ]
