# Generated by Django 5.2 on 2025-06-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0012_alter_curso_nivel_alter_juegos_dificultad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='nivel',
            field=models.CharField(choices=[('avanzado', 'Avanzado'), ('medio', 'Medio'), ('principiante', 'Principiante')], max_length=50),
        ),
        migrations.AlterField(
            model_name='juegos',
            name='dificultad',
            field=models.CharField(choices=[('dificil', 'Dificil'), ('intermedio', 'Intermedio'), ('facil', 'Facil')], max_length=50),
        ),
    ]
