# Generated by Django 5.2 on 2025-06-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0017_alter_curso_nivel_alter_juegos_dificultad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='nivel',
            field=models.CharField(choices=[('principiante', 'Principiante'), ('avanzado', 'Avanzado'), ('medio', 'Medio')], max_length=50),
        ),
        migrations.AlterField(
            model_name='juegos',
            name='dificultad',
            field=models.CharField(choices=[('facil', 'Facil'), ('intermedio', 'Intermedio'), ('dificil', 'Dificil')], max_length=50),
        ),
    ]
