# Generated by Django 5.2 on 2025-06-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0021_alter_curso_nivel_alter_juegos_dificultad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='nivel',
            field=models.CharField(choices=[('medio', 'Medio'), ('principiante', 'Principiante'), ('avanzado', 'Avanzado')], max_length=50),
        ),
        migrations.AlterField(
            model_name='juegos',
            name='dificultad',
            field=models.CharField(choices=[('dificil', 'Dificil'), ('facil', 'Facil'), ('intermedio', 'Intermedio')], max_length=50),
        ),
    ]
