# Generated by Django 5.2 on 2025-06-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0023_alter_curso_nivel_alter_juegos_dificultad'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='descripcion_larga',
            field=models.TextField(default='Bomboclat probando para una descripcion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='curso',
            name='nivel',
            field=models.CharField(choices=[('principiante', 'Principiante'), ('medio', 'Medio'), ('avanzado', 'Avanzado')], max_length=50),
        ),
        migrations.AlterField(
            model_name='juegos',
            name='dificultad',
            field=models.CharField(choices=[('intermedio', 'Intermedio'), ('dificil', 'Dificil'), ('facil', 'Facil')], max_length=50),
        ),
    ]
